// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconMdi:heart': typeof import('~icons/mdi/heart')['default']
    'IconMdi:menu': typeof import('~icons/mdi/menu')['default']
    'IconTwemoji:heart': typeof import('~icons/twemoji/heart')['default']
    'IconTwemoji:redHeart': typeof import('~icons/twemoji/red-heart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
